/* TERMS(이용약관 테이블) 생성 쿼리 */
CREATE TABLE TERMS (
    TERMS_NO BIGINT NOT NULL COMMENT '애플리케이션 이용 약관 번호, 1~100:테스트용 번호, 101~:운영데이터 번호',
    USE_YN TINYINT NOT NULL DEFAULT 1 COMMENT '사용 여부(1:사용, 0:미사용)',
    REQUIRE_YN TINYINT NOT NULL DEFAULT 1 COMMENT '필수 여부(1:필수, 0:선택)',
    ORDER_NO BIGINT NOT NULL DEFAULT 9999 COMMENT '출력 순서(작을수록 먼저 출력)',
    TITLE VARCHAR(2000) NOT NULL COMMENT '제목',
    CONTENTS LONGTEXT NOT NULL COMMENT '내용',
    CREATE_ID BIGINT NOT NULL COMMENT '생성한 회원 아이디',
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
    UPDATE_ID BIGINT COMMENT '수정한 회원 아이디',
    UPDATE_DATE DATETIME COMMENT '수정일자',
    CONSTRAINT TERMS_PK PRIMARY KEY(TERMS_NO)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='애플리케이션 이용 약관 정보를 저장하는 테이블';