/* MEMBER(회원 테이블) 생성 쿼리 */
CREATE TABLE MEMBER (
    MEMBER_ID BIGINT NOT NULL COMMENT '회원 아이디',
    ACCOUNT VARCHAR(10) UNIQUE NOT NULL COMMENT '회원 계정',	-- 10 * 4byte
    ACTIVE CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '활성화 여부(Y:활성화, N:비활성화)',
    PASSWORD VARCHAR(100) NOT NULL COMMENT '비밀번호(암호화된 문자열)',	-- 100 * 4byte
    NAME VARCHAR(100) NOT NULL COMMENT '이름',	-- 100 * 4byte
    BIRTH VARCHAR(2) NOT NULL COMMENT '생년월일(ex. 19901231)',	-- 2 * 4byte
    GENDER CHAR(1) NOT NULL COMMENT '성별(M:남성, W:여성)',
    EMAIL VARCHAR(200) UNIQUE NOT NULL COMMENT '회원 이메일',	-- 200 * 4byte
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL COMMENT '회원 휴대전화 번호',	-- 10 * 4byte
    POST_NUMBER VARCHAR(5) COMMENT '우편번호',	-- 5 * 4byte
    ADDRESS LONGTEXT COMMENT '주소',
    CREATE_ID BIGINT NOT NULL COMMENT '생성한 회원 아이디',
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
    UPDATE_ID BIGINT COMMENT '수정한 회원 아이디',
    UPDATE_DATE DATETIME COMMENT '수정일자',
    LOGIN_FAILED_COUNT BIGINT DEFAULT 0 COMMENT '로그인 실패 횟수',
    LATEST_LOGOUT_DATE DATETIME COMMENT '마지막 로그아웃 날짜',
    CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='애플리케이션의 회원 정보를 저장하는 테이블';