= Auth API Documentation (Auth API 문서)
https://github.com/InmookJeong/auth (auth 프로젝트 Repository)
:doctype: restTest
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Home-API]]
== 1. Home API

[[home-기본-조회]]
=== (1) Home 조회

==== # 다국어 한글 적용
operation::home/ko[snippets='http-request,http-response,response-fields']

==== # 다국어 영어 적용
operation::home/en[snippets='http-request,http-response,response-fields']

[[이용약관-API]]
== 2. 이용약관 API

=== (1) 이용약관 상세 조회

==== # 잘못된 이용약관 번호(TermsNO)가 전달되었을 경우

===== ## 다국어 한글 적용
operation::terms/search/one/search-by-unvaild-terms-no/ko[snippets='http-request,http-response,response-fields']

===== ## 다국어 영어 적용
operation::terms/search/one/search-by-unvaild-terms-no/en[snippets='http-request,http-response,response-fields']

==== # 올바른 이용약관 번호(TermsNO)가 전달되었지만 이용약관 데이터를 찾을 수 없는 경우

===== ## 다국어 한글 적용
operation::terms/search/one/terms-not-found/ko[snippets='http-request,http-response,response-fields']

===== ## 다국어 영어 적용
operation::terms/search/one/terms-not-found/en[snippets='http-request,http-response,response-fields']

==== # 이용약관 데이터를 찾은 경우
operation::terms/search/one/search-terms[snippets='http-request,http-response,response-fields']